import TableRow from '@material-ui/core/TableRow';
import Table from 'components/tables/components/Table';
import TableBody from 'components/tables/components/TableBody';
import TableContainer from 'components/tables/components/TableContainer';
import TableHead from 'components/tables/components/TableHead';
import TableHeadCell from 'components/tables/components/TableHeadCell';
import React from 'react';
import { useTranslation } from 'react-i18next';
import styled from 'styled-components';
import DataChannelIntegrationRow from './DataChannelIntegrationRow';

const StyledTable = styled(Table)`
  min-width: 850px;
`;

const StyledTableHeadCell = styled(TableHeadCell)`
  padding: 7px 16px;
`;

interface DataChannelIntegrationParams {
  description: string;
  fieldName: string;
  shouldAutoGenerate?: boolean;
  hideAutoGenerateCheckbox?: boolean;
  hide?: boolean;
}

interface Props {
  canDomainAutoGenerateIntegrationIds?: boolean;
  dataChannels?: DataChannelIntegrationParams[];
}

const IntegrationParametersAsTable = ({
  canDomainAutoGenerateIntegrationIds,
  dataChannels,
}: Props) => {
  const { t } = useTranslation();

  return (
    <TableContainer>
      <StyledTable aria-label="integration parameters table">
        <TableHead>
          <TableRow>
            <StyledTableHeadCell>
              {t('ui.common.datachannel', 'Data Channel')}
            </StyledTableHeadCell>
            <StyledTableHeadCell>
              {t(
                'ui.integrationParameters.enableIntegration',
                'Enable Integration'
              )}
            </StyledTableHeadCell>
            <StyledTableHeadCell>
              {t(
                'ui.integrationParameters.autoGenerateDataChannelIntegrationId',
                'Auto-Generate Integration ID'
              )}
            </StyledTableHeadCell>
            <StyledTableHeadCell>
              {t(
                'ui.integrationParameters.dataChannelIntegrationId',
                'Data Channel Integration ID'
              )}
            </StyledTableHeadCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {dataChannels
            ?.filter((channel) => !channel.hide)
            .map((channel) => (
              <DataChannelIntegrationRow
                key={channel.description}
                headerText={channel.description}
                fieldName={channel.fieldName}
                showAutoGenerateCheckbox={
                  canDomainAutoGenerateIntegrationIds &&
                  !channel.hideAutoGenerateCheckbox
                }
                disableIntegrationId={channel.shouldAutoGenerate}
              />
            ))}
        </TableBody>
      </StyledTable>
    </TableContainer>
  );
};

export default IntegrationParametersAsTable;
