import { QueryClient } from 'react-query';

export enum APIQueryKey {
  // General
  retrieveCurrentUserAccessibleDomains = 'retrieveCurrentUserAccessibleDomains',
  retrieveSiteEditComponentsById = 'retrieveSiteEditComponentsById',
  verifyPasswordStrength = 'verifyPasswordStrength',

  // Admin app
  getAssetGroupsForDomain = 'getAssetGroupsForDomain',
  getConvertedVolumetricValue = 'getConvertedVolumetricValue',
  getDisplayUnitsByUnitConversionMode = 'getDisplayUnitsByUnitConversionMode',
  getDomainNotes = 'getDomainNotes',
  getFtpDomains = 'getFtpDomains',
  getFileRtuDetails = 'getFileRtuDetails',
  getGenerateDataChannelMapPoints = 'getGenerateDataChannelMapPoints',
  getUserRolesForDomain = 'getUserRolesForDomain',
  getUserByUserId = 'getUserByUserId',
  retrieveRosterList = 'retrieveRosterList',
  retrieveGeoAreaList = 'retrieveGeoAreaList',
  getRosterDetails = 'getRosterDetails',
  getDataChannelDetailsById = 'getDataChannelDetailsById',
  get400SeriesPackets = 'get400SeriesPackets',
  getDataChannelEventsByDataChannelId = 'getDataChannelEventsByDataChannelId',
  getEventRuleGroupsByEventRuleGroupId = 'getEventRuleGroupsByEventRuleGroupId',
  getPublishedDomains = 'getPublishedDomains',
  getPublishedCommentsByDomainId = 'getPublishedCommentsByDomainId',
  getMessageTemplateList = 'getMessageTemplateList',
  getMessageTemplateDetails = 'getMessageTemplateDetails',
  getMessageTemplateContentOptions = 'getMessageTemplateContentOptions',
  getModbusCallHistory = 'getModbusCallHistory',
  getModbusCommLogSessionHistory = 'getModbusCommLogSessionHistory',
  getMetron2CallHistory = 'getMetron2CallHistory',
  getMetron2CommLogSessionHistory = 'getMetron2CommLogSessionHistory',
  retrieveMetronGeneralInformation = 'retrieveMetronGeneralInformation',
  getGeoAreaById = 'getGeoAreaById',
  getRtuChannelInfo = 'getRtuChannelInfo',
  getRtuCategory = 'getRtuCategory',
  getRawUnits = 'getRawUnits',
  getScaledUnits = 'getScaledUnits',
  getSmsRtuPackets = 'getSmsRtuPackets',
  getSiteInfoBySiteNumber = 'getSiteInfoBySiteNumber',
  getAuthenticationProviderForDomain = 'getAuthenticationProviderForDomain',
  retrieveAssetInfoRecords = 'retrieveAssetInfoRecords',
  retrieveAssetGroupInfoRecords = 'retrieveAssetGroupInfoRecords',
  retrieveAssetTreeInfoRecords = 'retrieveAssetTreeInfoRecords',
  retrieveDataChannelInfoRecords = 'retrieveDataChannelInfoRecords',
  retrieveDomainInfoRecords = 'retrieveDomainInfoRecords',
  retrieveProductRecords = 'retrieveProductRecords',
  retrieveRtuInfoRecords = 'retrieveRtuInfoRecords',
  rtuSearch = 'rtuSearch',
  retrieveRtuPollScheduleGroupRecords = 'retrieveRtuPollScheduleGroupRecords',
  retrieveSiteInfoRecords = 'retrieveSiteInfoRecords',
  retrieveTankDimensionInfoRecords = 'retrieveTankDimensionInfoRecords',
  retrievePollScheduleGroups = 'retrievePollScheduleGroups',
  retrieveHornerAnalogInputChannels = 'retrieveHornerAnalogInputChannels',
  getHornerCallHistory = 'getHornerCallHistory',
  getHornerCommLogSessionHistory = 'getHornerCommLogSessionHistory',
  getHornerDetailRecordTemplateList = 'getHornerDetailRecordTemplateList',
  getHornerTemplateList = 'getHornerTemplateList',
  retrieveHornerTransactionChannels = 'retrieveHornerTransactionChannels',
  // Operations App
  getAssetGroups = 'getAssetGroups',
  getAssetTreeNodeInfoListRootByDomain = 'getAssetTreeNodeInfoListRootByDomain',
  getDomainTags = 'getDomainTags',
  generateNewProblemReport = 'generateNewProblemReport',
  getUserWatchList = 'getUserWatchList',
  getProblemReportDetails = 'getProblemReportDetails',
  getProblemReportEmailAddresses = 'getProblemReportEmailAddresses',
  getProblemReportMessageTemplate = 'getProblemReportMessageTemplate',
  getProblemReportMessageTemplateOptions = 'getProblemReportMessageTemplateOptions',
  getProblemReportList = 'getProblemReportList',
  getProblemReportTags = 'getProblemReportTags',
  getRtuNotes = 'getRtuNotes',
  getSensorCalibration = 'getSensorCalibration',
  getTankSetup = 'getTankSetup',
  getUsageRateSummaryReport = 'getUsageRateSummaryReport',
  retrieveScheduledDeliveries = 'retrieveScheduledDeliveries',

  // Asset Details
  getLocationReadings = 'getLocationReadings',
  getLastKnownLocation = 'getLastKnownLocation',
  retrieveAssetDetailEventRules = 'retrieveAssetDetailEventRules',
  getDataChannelEventRuleRosters = 'getDataChannelEventRuleRosters',
  getRtuPollStatus = 'getRtuPollStatus',

  // Freezers App
  retrieveFreezerSites = 'retrieveFreezerSites',
  retrieveSiteDetails = 'retrieveSiteDetails',
  retrieveFreezerChartDetails = 'retrieveFreezerChartDetails',
  getDefaultChartList = 'getDefaultChartList',
  getFreezerDetails = 'getFreezerDetails',
  getDataChannelsByAssetId = 'getDataChannelsByAssetId',
  getTagListByAssetSubTypeId = 'getTagListByAssetSubTypeId',
  getFreezerChart = 'getFreezerChart',
  getDefaultChart = 'getDefaultChart',
  getChartsByAssetId = 'getChartsByAssetId',
  getBulkTankTagsBySiteId = 'getBulkTankTagsBySiteId',
  getHistoricalReadingsByBulkTankTagId = 'getHistoricalReadingsByBulkTankTagId',

  // Training App
  getTrainingVideos = 'getTrainingVideos',
}

export const queryClient = new QueryClient({
  defaultOptions: {
    // Queries defaults
    // https://react-query.tanstack.com/reference/useQuery
    queries: {
      // Don't retry failed queries by default
      retry: false,
      refetchOnWindowFocus: false,
    },
  },
});
