import Grid from '@material-ui/core/Grid';
import CheckboxWithLabel from 'components/forms/form-fields/CheckboxWithLabel';
import CustomTextField from 'components/forms/form-fields/CustomTextField';
import PageSubHeader from 'components/PageSubHeader';
import { Field } from 'formik';
import React from 'react';
import { useTranslation } from 'react-i18next';
import styled from 'styled-components';

const DataChannelHeader = styled(PageSubHeader)`
  & {
    font-size: 1.1rem;
  }
`;

interface Props {
  headerText: React.ReactNode;
  fieldPrefix: string;
  showAutoGenerateCheckbox?: boolean;
  disableIntegrationId?: boolean;
}

const DataChannelIntegration = ({
  headerText,
  fieldPrefix,
  showAutoGenerateCheckbox,
  disableIntegrationId,
}: Props) => {
  const { t } = useTranslation();

  return (
    <Grid container spacing={1}>
      <Grid item xs={12}>
        <DataChannelHeader dense>{headerText}</DataChannelHeader>
      </Grid>
      <Grid item xs={12}>
        <Field
          id={`${fieldPrefix}IntegrationDetails.enableIntegration-input`}
          component={CheckboxWithLabel}
          name={`${fieldPrefix}IntegrationDetails.enableIntegration`}
          Label={{
            label: t(
              'ui.integrationParameters.enableIntegration',
              'Enable Integration'
            ),
          }}
          type="checkbox"
        />
      </Grid>
      {showAutoGenerateCheckbox && (
        <Grid item xs={12}>
          <Field
            id={`${fieldPrefix}IntegrationDetails.shouldAutoGenerate-input`}
            component={CheckboxWithLabel}
            name={`${fieldPrefix}IntegrationDetails.shouldAutoGenerate`}
            Label={{
              label: t(
                'ui.integrationParameters.autoGenerateDataChannelIntegrationId',
                'Auto-Generate Data Channel Integration ID'
              ),
            }}
            type="checkbox"
          />
        </Grid>
      )}
      <Grid item xs={12}>
        <Field
          id={`${fieldPrefix}IntegrationDetails.integrationId-input`}
          component={CustomTextField}
          name={`${fieldPrefix}IntegrationDetails.integrationId`}
          label={t(
            'ui.integrationParameters.dataChannelIntegrationId',
            'Data Channel Integration ID'
          )}
          disabled={disableIntegrationId}
        />
      </Grid>
    </Grid>
  );
};

export default DataChannelIntegration;
